### ISSUE TITLE
error in the formation of the terrain

### ISSUE THREAD

**Issue by emaraboli2** [firetools/blenderfds#4] opened 2020-10-13 18:12 UTC
Hi everyone,
I did all the steps to generate the fds file with the terrain but I can't get the terrain to form correctly, holes and disturbances are created that will not let the simulation run properly, any idea what it can be or what I can do?
Thank you very much,
Enrique.
![image](https://user-images.githubusercontent.com/72820047/95899054-593e1c00-0d66-11eb-8dde-db819b7ccf5a.png)
![image](https://user-images.githubusercontent.com/72820047/95899083-66f3a180-0d66-11eb-98b3-9b6381f70e21.png)
![image](https://user-images.githubusercontent.com/72820047/95899097-6bb85580-0d66-11eb-8574-08a0a58048fe.png)

**Comment by emanuelegissi** [comment] 2020-10-14 04:32
Please, share your input files to have us taking a look. Emanuele

**Comment by emaraboli2** [comment] 2020-10-15 00:44
here are the files that I used
https://alumnosuaicl-my.sharepoint.com/:f:/g/personal/emaraboli_alumnos_uai_cl/EoisGwOOAblLv7LvFM5gtCcBmJNIkIxgNOdWNmEJynagtQ?e=uOhfBF

**Comment by emanuelegissi** [comment] 2020-10-15 07:32
Your dem seems ok. In this screenshot you have the QGIS file, the
BlenderFDS file, and the Smokeview visualization.
Please, use only the very latest versions of the tools, the development is
still ongoing.
[image: Schermata del 2020-10-15 09-30-14.png]
Here are the qgs, blend, and fds files that I obtained from it:
https://drive.google.com/drive/folders/1dMQ0myOJUE2-mUEKssXqh-6qCX47izh0?usp=sharing

**Comment by emaraboli2** [comment] 2020-10-23 15:59
Emanuele, can I work with & GEOM list group in the same way that it works when we use & OBST? because when I want to pass it from & GEOM to & OBST, in blenderfds, happens what I told you.

**Comment by emanuelegissi** [comment] 2020-10-23 18:27
Sorry i don't understand what you mean

**Comment by emanuelegissi** [comment] 2020-11-11 15:46
Many days have passed. I cannot reproduce the problem, no new data provided. I close the issue.

**Closed as completed by emanuelegissi** 2020-11-11 15:46 UTC
